### ISSUE TITLE
nimble genbook doesn't generate file locally

### ISSUE THREAD

**Issue by Clonkk** [SciNim/getting-started#9]
It seems since https://github.com/SciNim/getting-started/pull/8 using nimble genbook locally doesn't generate any files.

**Comment by Clonkk** [comment]
Issue was that apprently ``-d:nimibCustomPostInit `` in ``books/nim.cfg`` wasn't taken into account.

**Comment by pietroppeter** [comment]
I was able to generate the file locally but I can check again.

> Issue was

does this mean that the issue is solved?

**Comment by Clonkk** [comment]
"was" because I understood it but I still need to make a PR to update the nimble file so we are guaranted the -d: options is taken into accounts.

For my curiosity, why use a define with some expected variables instead of passing parameters to nbInit (with default value) ?

**Comment by pietroppeter** [comment]
> "was" because I understood it but I still need to make a PR to update the nimble file so we are guaranted the -d: options is taken into accounts.

ah right, I tend to use directly `nim r` instead of `nimble r`, maybe it was that... Is that why the define in nim.cfg is not used? And why does the CI seem to work in the end (although it didn't at first)?

> For my curiosity, why use a define with some expected file instead of passing parameters to nbInit (with default value) ?

Well, in this way if I have a bunch of files that do not have a configuration I can apply a custom configuration all at once without changing the `nbInit` in all files (true story from when I want all of my adventofnim to pass from default to darkMode).

The define mechanism is something that can probably evolve. In fact I am thinking that by default it should include any `nbPostInit.nim` that it finds between `nbThisDir` and `nbHomeDir` (similar to how nim processes config files). And actually probably the `nbPostInit.nim` should be just renamed as `nbcfg.nim`. The fact that it is named `nbPostInit` is it because in prinicple there is also a `nbPreSave` mechanism in place but I have not used it yet (the idea was that in presave you could put stuff that depends on what happen after nbInit, but maybe it is not a good idea). A define mechanism could be introduced to opt out.

Also I did have issues when trying templates and default values (my learning back then was to use overload for templates instead of having values with default, but I did try to avoid them for a while).

Anyway all this remarks about the api are most welcome, it is quite possible that it is not at all optimal in its current state. :)

**Comment by Clonkk** [comment]
> ah right, I tend to use directly nim r instead of nimble r, maybe it was that... Is that why the define in nim.cfg is not used? And why does the CI seem to work in the end (although it didn't at first)?

Config files works in mysterious way. I'm not sure of the "why" probably due the order of config files ?  

> Well, in this way if I have a bunch of files that do not have a configuration I can apply a custom configuration all at once without changing the nbInit in all files (true story from when I wanted all of my adventofnim to pass from default to darkMode).

I think it would be cleaner to use an init with a ``mixin`` symbol,  default const values declared as ``strdefine`` to be override-able at compile time. 
I'll take a look at the init, and see what I can come up with (see you in the nimib repo :sunglasses: )

**Comment by Clonkk** [comment]
closed with #11
